[package]
name = "rint"
version = "0.1.0"
edition = "2024"

[dependencies]
insta = "1.47.2"
derive_more = { version = "2.1.1", features = [ "full" ] }
serde = { version = "1.0.228", features = ["derive"] }
itertools = "0.14.0"
clap = { version = "4.6.1", features = ["color", "derive", "error-context", "help", "suggestions", "usage"] }
env_logger = "0.11.10"
log = "0.4.29"
clap-verbosity-flag = "3.0.4"
colored = "3.1.1"
lasso = "0.7.3"

[dev-dependencies]
insta = { version = "1.47.2", features = ["yaml"] }
