use crate::location::Located;
use std::fmt;

#[derive(Eq, PartialEq, Clone, Debug)]
pub enum Token {
    Plus,
    Minus,
    Times,
    Div,
    Mod,
    RShift, // bit shifts not implemented
    LShift, // bit shifts not implemented
    Less,
    Greater,
    NotEq,
    Exclam,
    BitAnd,
    BitOr,
    BitXor,
    LogicAnd,
    LogicOr,
    EqualEq,
    LessEq,
    GreaterEq,

    PlusEq,
    MinusEq,
    TimesEq,
    DivEq,
    ModEq,
    LShiftEq,
    RShiftEq,
    OrEq,
    XorEq,
    AndEq,
    Eq,

    Num(i32),

    Ident(String),
    LParen,
    RParen,
    LBrace,
    RBrace,
    Semicolon,
    Question,
    Colon,
    Comma,

    Struct,
    Typedef,
    If,
    Else,
    While,
    For,
    Continue,
    Break,
    Return,
    Assert,
    True,
    False,
    Null,
    Alloc,
    AllocArray,
    Int,
    Bool,
    Void,
    Char,
    String,
    DoubleMinus,
    DoublePlus,

    Eof,
}

pub type LToken = Located<Token>;

pub fn string_to_keyword(s: &str) -> Option<Token> {
    match s {
        "struct" => Some(Token::Struct),
        "typedef" => Some(Token::Typedef),
        "if" => Some(Token::If),
        "else" => Some(Token::Else),
        "while" => Some(Token::While),
        "for" => Some(Token::For),
        "continue" => Some(Token::Continue),
        "break" => Some(Token::Break),
        "return" => Some(Token::Return),
        "assert" => Some(Token::Assert),
        "true" => Some(Token::True),
        "false" => Some(Token::False),
        "NULL" => Some(Token::Null),
        "alloc" => Some(Token::Alloc),
        "alloc_array" => Some(Token::AllocArray),
        "int" => Some(Token::Int),
        "bool" => Some(Token::Bool),
        "void" => Some(Token::Void),
        "char" => Some(Token::Char),
        "string" => Some(Token::String),
        _ => None,
    }
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Token::Plus => "+".to_string(),
            Token::Minus => "-".to_string(),
            Token::Times => "*".to_string(),
            Token::Div => "/".to_string(),
            Token::Mod => "%".to_string(),
            Token::Exclam => "!".to_string(),
            Token::BitAnd => "&".to_string(),
            Token::BitOr => "|".to_string(),
            Token::BitXor => "^".to_string(),
            Token::LogicAnd => "&&".to_string(),
            Token::LogicOr => "||".to_string(),

            Token::TimesEq => "*=".to_string(),
            Token::PlusEq => "+=".to_string(),
            Token::MinusEq => "-=".to_string(),
            Token::DivEq => "/=".to_string(),
            Token::ModEq => "%=".to_string(),
            Token::Eq => "=".to_string(),

            Token::LParen => "(".to_string(),
            Token::RParen => ")".to_string(),
            Token::LBrace => "{".to_string(),
            Token::RBrace => "}".to_string(),
            Token::Semicolon => ";".to_string(),
            Token::Comma => ",".to_string(),

            Token::Struct => "struct".to_string(),
            Token::Typedef => "typedef".to_string(),
            Token::If => "if".to_string(),
            Token::Else => "else".to_string(),
            Token::While => "while".to_string(),
            Token::For => "for".to_string(),
            Token::Continue => "continue".to_string(),
            Token::Break => "break".to_string(),
            Token::Return => "return".to_string(),
            Token::Assert => "assert".to_string(),
            Token::True => "true".to_string(),
            Token::False => "false".to_string(),
            Token::Null => "NULL".to_string(),
            Token::Alloc => "alloc".to_string(),
            Token::AllocArray => "alloc_array".to_string(),
            Token::Int => "int".to_string(),
            Token::Bool => "bool".to_string(),
            Token::Void => "void".to_string(),
            Token::Char => "char".to_string(),
            Token::String => "string".to_string(),
            Token::DoubleMinus => "--".to_string(),

            Token::Ident(sym) => sym.clone(),
            Token::Num(n) => n.to_string(),

            Token::Eof => "EOF".to_string(),
            Token::RShift => ">>".to_string(),
            Token::LShift => "<<".to_string(),
            Token::Less => "<".to_string(),
            Token::Greater => ">".to_string(),
            Token::NotEq => "!=".to_string(),
            Token::EqualEq => "==".to_string(),
            Token::LessEq => "<=".to_string(),
            Token::GreaterEq => ">=".to_string(),
            Token::LShiftEq => "<<=".to_string(),
            Token::RShiftEq => ">>=".to_string(),
            Token::OrEq => "|=".to_string(),
            Token::XorEq => "^=".to_string(),
            Token::AndEq => "&=".to_string(),
            Token::Question => "?".to_string(),
            Token::Colon => ":".to_string(),
            Token::DoublePlus => "++".to_string(),
        };

        write!(f, "{}", s)
    }
}
